# Generated by Django 3.0.6 on 2020-05-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200531_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_comment',
        ),
    ]
